import type { VercelRequest, VercelResponse } from '@vercel/node';
import nodemailer from 'nodemailer';

export default async function handler(
  req: VercelRequest,
  res: VercelResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { from, to, message } = req.body;

    if (!from || !to || !message) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    if (from.length > 100 || to.length > 100 || message.length > 2000) {
      return res.status(400).json({ error: 'Payload too large' });
    }

    const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, ADMIN_EMAILS } = process.env;

    if (!SMTP_HOST || !SMTP_PORT || !SMTP_USER || !SMTP_PASS || !ADMIN_EMAILS) {
      console.error("Missing SMTP environment variables");
      return res.status(500).json({ error: 'Server configuration error' });
    }

    const adminEmails = ADMIN_EMAILS.split(',').map((email) => email.trim());
    const transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: Number(SMTP_PORT),
      secure: Number(SMTP_PORT) === 465, // true for 465, false for other ports
      auth: {
        user: SMTP_USER,
        pass: SMTP_PASS,
      },
    });

    const safeFrom = from.replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const safeTo = to.replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const safeMessage = message.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br/>');

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Anonymous Message</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f4f4f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
  <div style="max-width: 600px; margin: 40px auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);">
    <!-- Header -->
    <div style="background-color: #4f46e5; padding: 32px 24px; text-align: center;">
      <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600;">
        📨 New Anonymous Message
      </h1>
      <p style="color: #e0e7ff; margin: 8px 0 0 0; font-size: 15px;">
        A new submission was received on your website
      </p>
    </div>

    <!-- Content -->
    <div style="padding: 32px 24px;">
      <!-- Sender Card -->
      <div style="margin-bottom: 24px;">
        <span style="display: block; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px;">Sender</span>
        <div style="background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 16px;">
          <p style="margin: 0; color: #111827; font-size: 16px;">${safeFrom}</p>
        </div>
      </div>

      <!-- Recipient Card -->
      <div style="margin-bottom: 24px;">
        <span style="display: block; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px;">Recipient</span>
        <div style="background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px 16px;">
          <p style="margin: 0; color: #111827; font-size: 16px;">${safeTo}</p>
        </div>
      </div>

      <!-- Message Card -->
      <div style="margin-bottom: 24px;">
        <span style="display: block; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px;">Message</span>
        <div style="background-color: #eef2ff; border: 1px solid #c7d2fe; border-radius: 8px; padding: 20px;">
          <p style="margin: 0; color: #1e1b4b; font-size: 16px; line-height: 1.6;">
            ${safeMessage}
          </p>
        </div>
      </div>

      <!-- Timestamp -->
      <div style="margin-bottom: 16px;">
        <span style="display: block; font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;">Submission Time</span>
        <p style="margin: 0; color: #4b5563; font-size: 14px;">
          ${new Date().toLocaleString('en-US', { timeZone: 'UTC', timeZoneName: 'short' })}
        </p>
      </div>
    </div>

    <!-- Footer -->
    <div style="background-color: #f9fafb; border-top: 1px solid #e5e7eb; padding: 20px 24px; text-align: center;">
      <p style="margin: 0; color: #6b7280; font-size: 13px;">
        This email was automatically generated by your Anonymous Message Website.
      </p>
    </div>
  </div>
</body>
</html>
    `;

    const textContent = `
New Anonymous Message Received
------------------------------
Sender: ${from}
Recipient: ${to}

Message:
${message}

Submission Time: ${new Date().toLocaleString('en-US', { timeZone: 'UTC', timeZoneName: 'short' })}
------------------------------
This email was automatically generated by your Anonymous Message Website.
    `.trim();

    await transporter.sendMail({
      from: `"Anonymous Form" <${SMTP_USER}>`,
      to: adminEmails.join(','),
      subject: `📨 New Anonymous Message from ${from}`,
      text: textContent,
      html: htmlContent,
    });

    return res.status(200).json({ success: true, message: 'Email sent successfully' });
  } catch (error) {
    console.error('Error sending email:', error);
    return res.status(500).json({ error: 'Failed to send message' });
  }
}
